[package]
name = "positional_inverted_index"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
rand = "0.8.5"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"